# Generated by Django 5.2.2 on 2025-06-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='gateway_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
